name: my_flutter_local_notify
description: "A new Flutter project."
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  my_flutter:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
      ref: v1.1.5
  my_flutter_plugin:
    git:
      url: https://gitee.com/luoyi666/my_flutter_plugin.git
      ref: v1.1.5
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
