name: build example web page

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          architecture: x64
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      - run: sh ./script/example.sh
      - name: Releases apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "example/build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.TOKEN }}
